name: Build

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-debug:
    name: Build Debug
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: >
          msbuild Creature.sln
          /t:Restore
          /p:RestorePackagesConfig=true

      - name: Build
        run: >
          msbuild Creature.sln
          /m
          /p:Configuration=Debug
          /p:Platform=x64
          
      - name: Run Unit Tests
        run: .\x64\Debug\CreatureCoreUnitTest.exe
  
  build-release:
    name: Build Release
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: >
          msbuild Creature.sln
          /t:Restore
          /p:RestorePackagesConfig=true

      - name: Build
        run: >
          msbuild Creature.sln
          /m
          /p:Configuration=Release
          /p:Platform=x64

  clang-tidy:
    name: Clang-Tidy
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Restore NuGet packages
        run: >
          msbuild Creature.sln
          /t:Restore
          /p:RestorePackagesConfig=true
          
      - name: Run Clang-Tidy
        run: >
          msbuild Creature.sln
          /m
          /t:Rebuild
          /p:Configuration=Debug
          /p:Platform=x64
          /p:RunCodeAnalysis=true
