name: Build

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build-debug:
    name: Build Debug
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: microsoft/setup-msbuild@v2

      - name: Build
        run: >
          msbuild Creature.sln
          /m
          /p:Configuration=Debug
          /p:Platform=x64

  build-release:
    name: Build Release
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: microsoft/setup-msbuild@v3
        with:
          vs-version: '[17.0,18.0)'
          msbuild-architecture: x64

      - name: Build
        run: >
          msbuild Creature.sln
          /m
          /p:Configuration=Release
          /p:Platform=x64

  clang-tidy:
    name: Clang-Tidy
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: microsoft/setup-msbuild@v2

      - name: Run Clang-Tidy
        run: >
          msbuild Creature.sln
          /m
          /t:Rebuild
          /p:Configuration=Debug
          /p:Platform=x64
          /p:RunCodeAnalysis=true
          /p:EnableClangTidyCodeAnalysis=true
          /p:EnableMicrosoftCodeAnalysis=false